{
	"rolloutRegionName": "2ABN-02",
	"rolloutRegionType": "RR",
	"nbnLocations": [{
			"nbnLocationId": "LOC000076447025",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000076447025",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2525",
				"planNumber": null,
				"roadNumber1": "10",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528098.53812642 -3995017.68121906)",
				"formattedAddress": "10 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "10",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2525",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57775900",
			"longitude": "150.76539800",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": "FFL Include - MDU CA",
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2525",
				"planNumber": null,
				"roadNumber1": "10",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528098.49786769 -3995017.69254086)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000061088993",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000061088993",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2544",
				"planNumber": null,
				"roadNumber1": "11",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528171.56920257 -3995070.75055364)",
				"formattedAddress": "11 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "11",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2544",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57814700",
			"longitude": "150.76626700",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2544",
				"planNumber": null,
				"roadNumber1": "11",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528171.60495909 -3995070.70405274)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000084285046",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000084285046",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2526",
				"planNumber": null,
				"roadNumber1": "12",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528091.42531897 -3995037.69155667)",
				"formattedAddress": "12 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "12",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2526",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57794700",
			"longitude": "150.76535000",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": "MDU CA",
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2526",
				"planNumber": null,
				"roadNumber1": "12",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528091.39155272 -3995037.66137394)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": "MDU CA"
			}
		}, {
			"nbnLocationId": "LOC000017372176",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000017372176",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2543",
				"planNumber": null,
				"roadNumber1": "13",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528157.05169305 -3995084.07979591)",
				"formattedAddress": "13 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "13",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2543",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "11/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57828400",
			"longitude": "150.76612900",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": "MATCHED",
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": "FFL Include - MDU CA",
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2543",
				"planNumber": null,
				"roadNumber1": "13",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528157.08588018 -3995084.05873293)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000099658696",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000099658696",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2527",
				"planNumber": null,
				"roadNumber1": "14",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": "2527",
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528097.30824637 -3995057.7732487)",
				"formattedAddress": "14 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "14",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2527",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "03/08/2015",
				"mduCA": null
			},
			"latitude": "-34.57812000",
			"longitude": "150.76544300",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": "MATCHED",
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": "FFL Include - MDU CA",
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2527",
				"planNumber": null,
				"roadNumber1": "14",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528097.35215698 -3995057.72784192)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000070713327",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000070713327",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2542",
				"planNumber": null,
				"roadNumber1": "15",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528162.49888365 -3995100.53457444)",
				"formattedAddress": "15 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "15",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2542",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57842500",
			"longitude": "150.76621200",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": "MATCHED",
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2542",
				"planNumber": null,
				"roadNumber1": "15",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528162.46695039 -3995100.55258918)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000045272043",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000045272043",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2528",
				"planNumber": null,
				"roadNumber1": "16",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528103.82057851 -3995076.60123778)",
				"formattedAddress": "16 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "16",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2528",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57828100",
			"longitude": "150.76554100",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2528",
				"planNumber": null,
				"roadNumber1": "16",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528103.83461371 -3995076.55851252)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000018057353",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000018057353",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2541",
				"planNumber": null,
				"roadNumber1": "17",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528171.1271028 -3995115.96658883)",
				"formattedAddress": "17 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "17",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2541",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57855300",
			"longitude": "150.76632800",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2541",
				"planNumber": null,
				"roadNumber1": "17",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528171.14804466 -3995115.91363896)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000040568560",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000040568560",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2529",
				"planNumber": null,
				"roadNumber1": "18",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": "2529",
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528110.37219219 -3995093.76177849)",
				"formattedAddress": "18 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "18",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2529",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "03/08/2015",
				"mduCA": null
			},
			"latitude": "-34.57842700",
			"longitude": "150.76563700",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2529",
				"planNumber": null,
				"roadNumber1": "18",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528110.41125457 -3995093.71126045)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000007211889",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000007211889",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2540",
				"planNumber": null,
				"roadNumber1": "19",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528173.38567403 -3995135.5619449)",
				"formattedAddress": "19 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "19",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2540",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "11/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57872600",
			"longitude": "150.76638100",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2540",
				"planNumber": null,
				"roadNumber1": "19",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528173.34249909 -3995135.60186917)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000035678955",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000035678955",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2530",
				"planNumber": null,
				"roadNumber1": "20",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528116.39485786 -3995110.73982796)",
				"formattedAddress": "20 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "20",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2530",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57857200",
			"longitude": "150.76572700",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2530",
				"planNumber": null,
				"roadNumber1": "20",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528116.40450339 -3995110.77792001)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000084044716",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000084044716",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2531",
				"planNumber": null,
				"roadNumber1": "22",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528122.77991417 -3995127.76652476)",
				"formattedAddress": "22 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "22",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2531",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "12/02/2016",
				"mduCA": null
			},
			"latitude": "-34.57871700",
			"longitude": "150.76582100",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": "MATCHED",
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2531",
				"planNumber": null,
				"roadNumber1": "22",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528122.7826599 -3995127.73232075)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}, {
			"nbnLocationId": "LOC000087397056",
			"quarantine": "FALSE",
			"sourceContributorId": "PNI:LOC000087397056",
			"physicalAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": "",
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2532",
				"planNumber": null,
				"roadNumber1": "24",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": "2532",
				"postcode": "2527",
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528129.21144412 -3995145.13401845)",
				"formattedAddress": "24 ABERCROMBIE CR, ALBION PARK NSW 2527",
				"roadNumberFirst": {
					"prefix": null,
					"number": "24",
					"suffix": null,
					"type": "CR"
				},
				"addressUnitNumber": {
					"prefix": null,
					"number": null,
					"suffix": null,
					"type": null
				},
				"addressLotNumber": {
					"prefix": null,
					"number": "2532",
					"suffix": null,
					"type": null
				},
				"lastUpdateDate": "03/08/2015",
				"mduCA": null
			},
			"latitude": "-34.57886500",
			"longitude": "150.76591600",
			"serviceable": "Y",
			"premiseDa": "Y",
			"premiseSoe": "Y",
			"isNonPremise": "N",
			"locationStatus": "ACTIVE",
			"locationType": "SITE",
			"isVacantLand": "FALSE",
			"marketable": "Y",
			"tlsMatchingStatus": null,
			"tlsInteractionStatus": "TLS 1.1",
			"excluded": "N",
			"tlsExcludeReason": null,
			"tlsRemovalReason": null,
			"containment": null,
			"inGreenfields": "Y",
			"inAsa": "N",
			"isTelstraVelocity": "N",
			"serviceClassCode": "10",
			"serviceClassDescription": "Planned to be serviced by Copper (as yet not serviceable)",
			"orderId": null,
			"orderType": null,
			"orderStatus": null,
			"orderDueDate": null,
			"avcId": null,
			"infill": null,
			"scr": null,
			"previousRrName": "2ABN-02",
			"previousRrType": "RR",
			"currentRrName": "2ABN-02",
			"samBoundaryName": null,
			"currentRrType": "SAM",
			"retiredWithdrawnDate": null,
			"duplicateLocation": "N",
			"poorlyGeocoded": "N",
			"mduCA": null,
			"fflAddress": {
				"secondaryComplexName": null,
				"unitTypeCode": null,
				"unitNumber": null,
				"levelTypeCode": null,
				"levelNumber": null,
				"complexRoadNumber1": null,
				"complexRoadNumber2": null,
				"complexRoadName": null,
				"complexRoadTypeCode": null,
				"complexRoadSuffixCode": null,
				"addressSiteName": null,
				"lotNumber": "2532",
				"planNumber": null,
				"roadNumber1": "24",
				"roadNumber2": null,
				"roadName": "ABERCROMBIE",
				"roadTypeCode": "CR",
				"roadSuffixCode": null,
				"localityName": "ALBION PARK",
				"locationDescriptor": null,
				"postcode": null,
				"stateTerritoryCode": "NSW",
				"deliveryPointIdentifier": "POINT (1528129.23495018 -3995145.16504947)",
				"lastUpdateDate": "21/10/2016",
				"mduCA": null
			}
		}
  ]
}
